IGNORE = [
    "manual\s+trans",
    "down\s+payment",
    "dealer",
    "dealership",
    "bad\s+credit",
    "pay\s+later",
    "credit",
    "down\s+payment",
    "fin.*ancing",
    "fin.*ance",
    "crédito",
    "only\s+trade",
    "trade\s+only",
    "approve",
    "ap.*roval",
    "document\s+need.*",
    "rebui.*",
    "reconstruido",
    "approv",
    "parts\s+car",
    "part\s+car",
    "not\s+part\s+out",
    "good\s+parts",
    "parting\s+out",
]

CONS = [
    "rebuil.*",
    "good parts",
    "van.*",
    "wagon",
    "bad engine",
    "not\s+start" "not\s+work.*",
    "not\s+run.*",
    "stopped\s+start",
    "not\s+mov",
    "transmission\s+slips",
    "bad\s+motor",
    "gasket",
    "inch",
    "not\s+drivable",
]
PROS = [
    "ford",
    "toyota",
    "chevrolet",
    "lexus",
    "honda",
    "nis.*an",
    "cadil.*ac",
]
