# Generated by Django 4.2.14 on 2024-07-16 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="kid",),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="admin", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
