# Generated by Django 4.2.14 on 2024-07-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_kid_user_role_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="id", new_name="iss",),
    ]
