# Generated by Django 4.2.14 on 2024-07-16 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_id_user_iss"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="iss",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
